# Generated by Django 6.0.1 on 2026-01-18 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FullBridgePhaseShiftConverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='FullBridgePhaseShiftConverter', max_length=100)),
                ('Vs_min', models.FloatField(default=260)),
                ('Vs_max', models.FloatField(default=420)),
                ('Vs_nom', models.FloatField(default=345)),
                ('Vo_min', models.FloatField(default=12)),
                ('Vo_max', models.FloatField(default=16)),
                ('Vo_nom', models.FloatField(default=14)),
                ('Io_min', models.FloatField(default=0)),
                ('Io_max', models.FloatField(default=230)),
                ('f', models.FloatField(default=200000)),
                ('ripple_Vo', models.FloatField(default=0.01)),
                ('Pout_max', models.FloatField(default=3200)),
            ],
        ),
        migrations.CreateModel(
            name='FullBridgePhaseShiftParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_max', models.FloatField(default=0.45)),
                ('D_theo', models.FloatField(default=0.5)),
                ('Lk', models.FloatField(default=5e-07)),
                ('Lp', models.FloatField(default=0.000147)),
                ('Ns', models.PositiveIntegerField(default=16)),
                ('R_prim', models.FloatField(default=0.025)),
                ('R_sec', models.FloatField(default=0.001)),
                ('Rdson_PR', models.FloatField(default=0.18)),
                ('Rdson_SR', models.FloatField(default=0.002625)),
                ('RLo', models.FloatField(default=0.0025)),
                ('N_Lo', models.PositiveIntegerField(default=2)),
                ('C_oss', models.FloatField(default=1.2e-10)),
                ('C_tr', models.FloatField(default=1e-10)),
                ('delta_Us', models.FloatField(default=0.1)),
                ('V_cc', models.FloatField(default=12.0)),
                ('Qg_PR', models.FloatField(default=1.18e-10)),
                ('Qg_SR', models.FloatField(default=8.1e-11)),
                ('C_oss_SR', models.FloatField(default=1.04e-09)),
                ('Cm_3C90', models.FloatField(default=0.0032)),
                ('x_3C90', models.FloatField(default=1.46)),
                ('y_3C90', models.FloatField(default=2.75)),
                ('B_sat_3c90', models.FloatField(default=0.38)),
                ('Cm_3F3', models.FloatField(default=0.00025)),
                ('x_3F3', models.FloatField(default=1.63)),
                ('y_3F3', models.FloatField(default=2.45)),
                ('Ac_ferita', models.FloatField(default=130)),
                ('Vc', models.FloatField(default=5.3)),
                ('Ae_ER51', models.FloatField(default=351)),
                ('Vc_ER51', models.FloatField(default=25.8)),
                ('converter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_params', to='app23_PSFB_converter.fullbridgephaseshiftconverter')),
            ],
        ),
    ]
